name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # ou la branche que vous utilisez pour le déploiement

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Create config.js with secrets
        run: |
          echo "const firebaseConfig = {
            apiKey: '${{ secrets.API_KEY }}',
            authDomain: '${{ secrets.AUTH_DOMAIN }}',
            projectId: '${{ secrets.PROJECT_ID }}',
            storageBucket: '${{ secrets.STORAGE_BUCKET }}',
            messagingSenderId: '${{ secrets.MESSAGING_SENDER_ID }}',
            appId: '${{ secrets.APP_ID }}',
            measurementId: '${{ secrets.MEASUREMENT_ID }}'
          };
          export default firebaseConfig;" > config.js
          mkdir deploy
          cp -r * deploy/
          mv deploy/config.js deploy/config.js
        env:
          API_KEY: ${{ secrets.API_KEY }}
          AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
          MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
          APP_ID: ${{ secrets.APP_ID }}
          MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
