name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Create config.js with secrets
        run: |
          mkdir -p cours
          echo "const firebaseConfig = {
            apiKey: '${{ secrets.API_KEY }}',
            authDomain: '${{ secrets.AUTH_DOMAIN }}',
            projectId: '${{ secrets.PROJECT_ID }}',
            storageBucket: '${{ secrets.STORAGE_BUCKET }}',
            messagingSenderId: '${{ secrets.MESSAGING_SENDER_ID }}',
            appId: '${{ secrets.APP_ID }}',
            measurementId: '${{ secrets.MEASUREMENT_ID }}'
          };
          export default firebaseConfig;" > cours/config.js

      - name: Prepare deploy directory
        run: |
          mkdir deploy
          rsync -av --progress ./cours deploy/cours --exclude deploy --exclude .git --exclude .github

      - name: List files in deploy directory
        run: ls -la deploy/cours

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./deploy
